import type { Broker } from './types';

export const brokers: Broker[] = [
	// ─── CRUCIAL PRIORITY ────────────────────────────────────────────

	{
		id: 'spokeo',
		name: 'Spokeo',
		url: 'https://www.spokeo.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://www.spokeo.com/optout',
		emailAddress: 'privacy@spokeo.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'profileUrl'],
		searchUrl: 'https://www.spokeo.com/search',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		subsidiaries: ['thatsthem'],
		steps: [
			{ instruction: 'Search your name on Spokeo to find your profile.', url: 'https://www.spokeo.com/search' },
			{ instruction: 'Copy the full URL of your profile page from the address bar.' },
			{ instruction: 'Go to the Spokeo opt-out page.', url: 'https://www.spokeo.com/optout' },
			{ instruction: 'Paste your profile URL and enter your email address.' },
			{ instruction: 'Complete the reCAPTCHA.', note: 'You may need to solve an image challenge.' },
			{ instruction: 'Click "Remove This Listing".' },
			{ instruction: 'Check your email and click the verification link.', note: 'Each listing requires a separate opt-out.' },
		],
		notes: 'Each profile listing must be removed individually. Check for variations of your name.',
	},
	{
		id: 'beenverified',
		name: 'BeenVerified',
		url: 'https://www.beenverified.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://www.beenverified.com/app/optout/search',
		emailAddress: 'privacy@beenverified.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email'],
		searchUrl: 'https://www.beenverified.com/app/optout/search',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'The Lifetime Value Company (LTVCO)',
		subsidiaries: ['peoplelooker', 'peoplesmart'],
		steps: [
			{ instruction: 'Go to the BeenVerified opt-out page.', url: 'https://www.beenverified.com/app/optout/search' },
			{ instruction: 'Enter your first name, last name, and state.' },
			{ instruction: 'Click Search and find your listing.' },
			{ instruction: 'Click "Proceed to Opt Out".' },
			{ instruction: 'Enter your email address and complete the CAPTCHA.' },
			{ instruction: 'Check your email and click "Verify Opt-Out".', note: 'For multiple records, email privacy@beenverified.com.' },
		],
		notes: 'Also removes from PeopleLooker and PeopleSmart (same parent company).',
	},
	{
		id: 'whitepages',
		name: 'WhitePages',
		url: 'https://www.whitepages.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://www.whitepages.com/suppression-requests',
		emailAddress: 'support@whitepages.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'phone', 'profileUrl'],
		searchUrl: 'https://www.whitepages.com',
		verificationMethod: 'phone',
		relistsAfterDays: 120,
		steps: [
			{ instruction: 'Search your name on WhitePages.', url: 'https://www.whitepages.com' },
			{ instruction: 'Click "View Details" on your profile and copy the URL.' },
			{ instruction: 'Go to the suppression request page.', url: 'https://www.whitepages.com/suppression-requests' },
			{ instruction: 'Paste your profile URL and click Next.' },
			{ instruction: 'Confirm the profile is yours and click "Remove Me".' },
			{ instruction: 'Select a reason for opt-out.' },
			{ instruction: 'Enter your phone number and click "Call Now To Verify".', note: 'You will receive an automated phone call with a verification code.' },
			{ instruction: 'Answer the call and enter the verification code shown on screen.' },
		],
		notes: 'Requires phone verification — you must answer an automated call.',
	},
	{
		id: 'intelius',
		name: 'Intelius',
		url: 'https://www.intelius.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://suppression.peopleconnect.us/login',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'dob'],
		searchUrl: 'https://www.intelius.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'PeopleConnect Holdings (H.I.G. Capital)',
		subsidiaries: ['truthfinder', 'instantcheckmate', 'zabasearch', 'ussearch', 'addresses'],
		steps: [
			{ instruction: 'Go to the PeopleConnect suppression center.', url: 'https://suppression.peopleconnect.us/login' },
			{ instruction: 'Enter your email address and click Continue.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Enter your date of birth and agree to the terms.' },
			{ instruction: 'Enter your full legal name (first, middle, last).' },
			{ instruction: 'Find and select your record.' },
			{ instruction: 'Choose "Suppressed" in the Desired Behavior dropdown.' },
			{ instruction: 'Click Save.', note: 'This suppresses your record across all PeopleConnect sites.' },
		],
		notes: 'Opting out here also covers TruthFinder, Instant Checkmate, Zabasearch, USSearch, and Addresses.com.',
	},
	{
		id: 'radaris',
		name: 'Radaris',
		url: 'https://radaris.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'hard',
		optOutMethod: 'form',
		optOutUrl: 'https://radaris.com/control/privacy',
		emailAddress: 'support@radaris.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'address', 'profileUrl'],
		searchUrl: 'https://radaris.com',
		verificationMethod: 'email',
		relistsAfterDays: 60,
		steps: [
			{ instruction: 'Search your name on Radaris and find your profile.', url: 'https://radaris.com' },
			{ instruction: 'Copy the full profile URL.' },
			{ instruction: 'Go to the Radaris privacy control page.', url: 'https://radaris.com/control/privacy' },
			{ instruction: 'Enter your full name, city, state, and profile URL.' },
			{ instruction: 'Click Next and confirm your identity.' },
			{ instruction: 'Click "Start Removing".' },
			{ instruction: 'Enter your email address.' },
			{ instruction: 'Complete the CAPTCHA.' },
			{ instruction: 'Check your email for a confirmation code and enter it.' },
		],
		notes: 'Multi-step process that can take 10-20 minutes. Re-lists frequently.',
	},
	{
		id: 'truepeoplesearch',
		name: 'TruePeopleSearch',
		url: 'https://www.truepeoplesearch.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://www.truepeoplesearch.com/removal',
		legalBasis: ['ccpa'],
		requiredInfo: ['email'],
		searchUrl: 'https://www.truepeoplesearch.com',
		verificationMethod: 'email',
		relistsAfterDays: 60,
		steps: [
			{ instruction: 'Go to the TruePeopleSearch removal page.', url: 'https://www.truepeoplesearch.com/removal' },
			{ instruction: 'Enter your email address.' },
			{ instruction: 'Check the box confirming you are the subject of the record.' },
			{ instruction: 'Submit the request.' },
			{ instruction: 'Check your email and click the verification link.', note: 'Data is continuously re-scraped — you may need to repeat this periodically.' },
		],
	},
	{
		id: 'fastpeoplesearch',
		name: 'FastPeopleSearch',
		url: 'https://www.fastpeoplesearch.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://www.fastpeoplesearch.com/removal',
		legalBasis: ['ccpa'],
		requiredInfo: ['email'],
		searchUrl: 'https://www.fastpeoplesearch.com',
		verificationMethod: 'email',
		relistsAfterDays: 60,
		steps: [
			{ instruction: 'Go to the FastPeopleSearch removal page.', url: 'https://www.fastpeoplesearch.com/removal' },
			{ instruction: 'Enter your email and agree to the removal authorization.' },
			{ instruction: 'Complete the CAPTCHA.', note: 'May need multiple attempts.' },
			{ instruction: 'Find your record and click "View Free Details".' },
			{ instruction: 'Click "Remove My Record".' },
			{ instruction: 'Complete the additional CAPTCHA.' },
			{ instruction: 'Check your email and click the verification link.' },
		],
	},
	{
		id: 'mylife',
		name: 'MyLife',
		url: 'https://www.mylife.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://www.mylife.com/ccpa/index.pubview',
		emailAddress: 'membersupport@mylife.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'profileUrl'],
		searchUrl: 'https://www.mylife.com',
		verificationMethod: 'email',
		relistsAfterDays: 30,
		steps: [
			{ instruction: 'Search your name on MyLife and find your profile.', url: 'https://www.mylife.com' },
			{ instruction: 'Copy the profile URL.' },
			{ instruction: 'Go to the MyLife CCPA opt-out page.', url: 'https://www.mylife.com/ccpa/index.pubview' },
			{ instruction: 'Fill out the required fields and paste your profile URL.' },
			{ instruction: 'Enter your email address.' },
			{ instruction: 'Complete the reCAPTCHA and click "Opt Out".' },
			{ instruction: 'Check your email for a verification code and enter it.' },
		],
		notes: 'Re-lists very quickly — may reappear within 30 days.',
	},
	{
		id: 'peoplefinder',
		name: 'PeopleFinders',
		url: 'https://www.peoplefinders.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://www.peoplefinders.com/opt-out',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email'],
		searchUrl: 'https://www.peoplefinders.com',
		verificationMethod: 'email',
		relistsAfterDays: 180,
		steps: [
			{ instruction: 'Go to the PeopleFinders opt-out page.', url: 'https://www.peoplefinders.com/opt-out' },
			{ instruction: 'Click "Next" under "Public Records Removal".' },
			{ instruction: 'Enter your full name and email, then complete the CAPTCHA.' },
			{ instruction: 'Click "Send Request".' },
			{ instruction: 'Check your email and click the verification link.', note: 'Link expires in 24 hours.' },
			{ instruction: 'Complete the Record Suppression Form with your personal details.' },
			{ instruction: 'Submit the form.' },
		],
	},
	{
		id: 'nuwber',
		name: 'Nuwber',
		url: 'https://nuwber.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://nuwber.com/removal/link',
		legalBasis: ['ccpa'],
		requiredInfo: ['email', 'profileUrl'],
		searchUrl: 'https://nuwber.com',
		verificationMethod: 'email',
		relistsAfterDays: 90,
		steps: [
			{ instruction: 'Search your name on Nuwber and find your listing.', url: 'https://nuwber.com' },
			{ instruction: 'Copy the full listing URL.' },
			{ instruction: 'Go to the Nuwber removal page.', url: 'https://nuwber.com/removal/link' },
			{ instruction: 'Paste the listing URL.' },
			{ instruction: 'Click "Opt Out".' },
			{ instruction: 'Enter your email address.' },
			{ instruction: 'Check your email and click "Confirm request".' },
		],
	},

	// ─── HIGH PRIORITY ───────────────────────────────────────────────

	{
		id: 'acxiom',
		name: 'Acxiom',
		url: 'https://www.acxiom.com',
		category: 'marketing',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://isapps.acxiom.com/optout/optout.aspx',
		legalBasis: ['ccpa', 'gdpr'],
		requiredInfo: ['name', 'email', 'address'],
		verificationMethod: 'email',
		parentCompany: 'Omnicom Group',
		steps: [
			{ instruction: 'Go to the Acxiom opt-out page.', url: 'https://isapps.acxiom.com/optout/optout.aspx' },
			{ instruction: 'Select all three opt-out segments: Mailing Addresses, Phone Numbers, Email Addresses.' },
			{ instruction: 'Under "Who is opting out?" select "Me".' },
			{ instruction: 'Fill in your personal details (name, address, etc.).' },
			{ instruction: 'Submit the form.' },
			{ instruction: 'Enter your email address and complete the CAPTCHA.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Complete the final CAPTCHA.', note: 'Processing takes up to 2 weeks.' },
		],
		notes: 'Acxiom is a behind-the-scenes data broker — there is no public profile to search for.',
	},
	{
		id: 'epsilon',
		name: 'Epsilon',
		url: 'https://www.epsilon.com',
		category: 'marketing',
		priority: 'high',
		difficulty: 'hard',
		optOutMethod: 'form',
		optOutUrl: 'https://legal.epsilon.com/dsr',
		emailAddress: 'privacy@epsilon.com',
		legalBasis: ['ccpa', 'gdpr'],
		requiredInfo: ['name', 'email', 'address'],
		verificationMethod: 'email',
		parentCompany: 'Publicis Groupe',
		steps: [
			{ instruction: 'Go to the Epsilon data subject request page.', url: 'https://legal.epsilon.com/dsr' },
			{ instruction: 'Select your country.' },
			{ instruction: 'Choose "Delete my Personal Information".' },
			{ instruction: 'Select "Consumer".' },
			{ instruction: 'Fill in your personal details (name, address, email).' },
			{ instruction: 'Complete the CAPTCHA and submit.', note: 'May require government ID and proof of address for identity verification.' },
		],
		notes: 'Identity verification may require uploading government ID. Processing takes up to 45 days.',
	},
	{
		id: 'lexisnexis',
		name: 'LexisNexis',
		url: 'https://www.lexisnexis.com',
		category: 'data-broker',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://optout.lexisnexis.com',
		legalBasis: ['ccpa', 'gdpr'],
		requiredInfo: ['name', 'address'],
		verificationMethod: 'none',
		parentCompany: 'RELX',
		steps: [
			{ instruction: 'Go to the LexisNexis opt-out page.', url: 'https://optout.lexisnexis.com' },
			{ instruction: 'Click Next.' },
			{ instruction: 'Read the instructions and click Next again.' },
			{ instruction: 'Select "I do not want my information shared" as your reason.' },
			{ instruction: 'Enter your personal details. You can skip the SSN field.' },
			{ instruction: 'Enter your complete address and click Next.' },
			{ instruction: 'Add a preferred contact method (optional).' },
			{ instruction: 'Click "Confirm Request" and save your confirmation number.', note: 'Processing takes up to 30 days.' },
		],
	},
	{
		id: 'thatsthem',
		name: "ThatsThem",
		url: 'https://thatsthem.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://thatsthem.com/optout',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'address', 'phone'],
		searchUrl: 'https://thatsthem.com',
		verificationMethod: 'none',
		parentCompany: 'Spokeo',
		steps: [
			{ instruction: 'Go to the ThatsThem opt-out page.', url: 'https://thatsthem.com/optout' },
			{ instruction: 'Enter your full name, email, address, city, state, ZIP, and phone.' },
			{ instruction: 'Complete the CAPTCHA.' },
			{ instruction: 'Click Submit.', note: 'Repeat for each variation of your record.' },
		],
	},
	{
		id: 'clustrmaps',
		name: 'ClustrMaps',
		url: 'https://clustrmaps.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://clustrmaps.com/bl/opt-out',
		emailAddress: 'support@clustrmaps.com',
		legalBasis: ['ccpa', 'gdpr'],
		requiredInfo: ['name', 'email', 'address', 'profileUrl'],
		searchUrl: 'https://clustrmaps.com',
		verificationMethod: 'none',
		steps: [
			{ instruction: 'Search your name on ClustrMaps and copy the listing URL.', url: 'https://clustrmaps.com' },
			{ instruction: 'Go to the ClustrMaps opt-out page.', url: 'https://clustrmaps.com/bl/opt-out' },
			{ instruction: 'Enter your full name, email, listing URL, and address.' },
			{ instruction: 'Check the boxes for information you want deleted.' },
			{ instruction: 'Click "Apply".', note: 'Processing is usually immediate.' },
		],
	},
	{
		id: 'cyberbackgroundchecks',
		name: 'CyberBackgroundChecks',
		url: 'https://www.cyberbackgroundchecks.com',
		category: 'background-check',
		priority: 'high',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://www.cyberbackgroundchecks.com/removal',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email'],
		searchUrl: 'https://www.cyberbackgroundchecks.com',
		verificationMethod: 'none',
		steps: [
			{ instruction: 'Go to the CyberBackgroundChecks removal page.', url: 'https://www.cyberbackgroundchecks.com/removal' },
			{ instruction: 'Enter your full name and email address.' },
			{ instruction: 'Check the Terms box.' },
			{ instruction: 'Complete the CAPTCHA.' },
			{ instruction: 'Click "Send Request".', note: 'Processing takes up to 3 days.' },
		],
	},
	{
		id: 'searchpeoplefree',
		name: 'SearchPeopleFree',
		url: 'https://www.searchpeoplefree.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://www.searchpeoplefree.com/opt-out',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email'],
		searchUrl: 'https://www.searchpeoplefree.com',
		verificationMethod: 'email',
		steps: [
			{ instruction: 'Go to the SearchPeopleFree opt-out page.', url: 'https://www.searchpeoplefree.com/opt-out' },
			{ instruction: 'Enter your email address and name, then complete the CAPTCHA.' },
			{ instruction: 'Check your email and click the link.', note: 'Link expires in 24 hours.' },
			{ instruction: 'Complete the opt-out form with your personal info.', note: 'You must finish within 30 minutes or the session expires.' },
			{ instruction: 'Submit the form.' },
		],
	},
	{
		id: 'cocofinder',
		name: 'CocoFinder',
		url: 'https://cocofinder.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'easy',
		optOutMethod: 'email+form',
		optOutUrl: 'https://cocofinder.com/remove-my-info',
		emailAddress: 'support@cocofinder.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'profileUrl'],
		searchUrl: 'https://cocofinder.com',
		verificationMethod: 'none',
		steps: [
			{ instruction: 'Search your name on CocoFinder and click "Check Details".', url: 'https://cocofinder.com' },
			{ instruction: 'Copy the URL from the address bar.' },
			{ instruction: 'Go to the CocoFinder removal page.', url: 'https://cocofinder.com/remove-my-info' },
			{ instruction: 'Click "filling out this form" to open the Google Docs removal form.' },
			{ instruction: 'Enter your full name, email, profile URL, and reason for removal.' },
			{ instruction: 'Submit the form.', note: 'Alternatively, email support@cocofinder.com with the same info.' },
		],
	},

	// ─── PEOPLECONNECT SUBSIDIARIES (share opt-out with Intelius) ────

	{
		id: 'truthfinder',
		name: 'TruthFinder',
		url: 'https://www.truthfinder.com',
		category: 'people-search',
		priority: 'crucial',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://suppression.peopleconnect.us/login',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'dob'],
		searchUrl: 'https://www.truthfinder.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'PeopleConnect Holdings (H.I.G. Capital)',
		steps: [
			{ instruction: 'Go to the PeopleConnect suppression center.', url: 'https://suppression.peopleconnect.us/login' },
			{ instruction: 'Enter your email address and click Continue.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Enter your date of birth and agree to the terms.' },
			{ instruction: 'Enter your full name and select your record.' },
			{ instruction: 'Choose "Suppressed" in the Desired Behavior dropdown and click Save.' },
		],
		notes: 'Uses the same PeopleConnect suppression center as Intelius. Opting out of Intelius covers this site.',
	},
	{
		id: 'instantcheckmate',
		name: 'Instant Checkmate',
		url: 'https://www.instantcheckmate.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://suppression.peopleconnect.us/login',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'dob'],
		searchUrl: 'https://www.instantcheckmate.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'PeopleConnect Holdings (H.I.G. Capital)',
		steps: [
			{ instruction: 'Go to the PeopleConnect suppression center.', url: 'https://suppression.peopleconnect.us/login' },
			{ instruction: 'Enter your email address and click Continue.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Enter your date of birth and agree to the terms.' },
			{ instruction: 'Enter your full name and select your record.' },
			{ instruction: 'Choose "Suppressed" in the Desired Behavior dropdown and click Save.' },
		],
		notes: 'Uses the same PeopleConnect suppression center as Intelius.',
	},
	{
		id: 'zabasearch',
		name: 'Zabasearch',
		url: 'https://www.zabasearch.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://suppression.peopleconnect.us/login',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'dob'],
		searchUrl: 'https://www.zabasearch.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'PeopleConnect Holdings (H.I.G. Capital)',
		steps: [
			{ instruction: 'Go to the PeopleConnect suppression center.', url: 'https://suppression.peopleconnect.us/login' },
			{ instruction: 'Enter your email address and click Continue.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Enter your date of birth and agree to the terms.' },
			{ instruction: 'Enter your full name and select your record.' },
			{ instruction: 'Choose "Suppressed" in the Desired Behavior dropdown and click Save.' },
		],
		notes: 'Uses the same PeopleConnect suppression center as Intelius.',
	},
	{
		id: 'ussearch',
		name: 'USSearch',
		url: 'https://www.ussearch.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://suppression.peopleconnect.us/login',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'dob'],
		searchUrl: 'https://www.ussearch.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'PeopleConnect Holdings (H.I.G. Capital)',
		steps: [
			{ instruction: 'Go to the PeopleConnect suppression center.', url: 'https://suppression.peopleconnect.us/login' },
			{ instruction: 'Enter your email address and click Continue.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Enter your date of birth and agree to the terms.' },
			{ instruction: 'Enter your full name and select your record.' },
			{ instruction: 'Choose "Suppressed" in the Desired Behavior dropdown and click Save.' },
		],
		notes: 'Uses the same PeopleConnect suppression center as Intelius.',
	},
	{
		id: 'addresses',
		name: 'Addresses.com',
		url: 'https://www.addresses.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'medium',
		optOutMethod: 'form',
		optOutUrl: 'https://suppression.peopleconnect.us/login',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email', 'dob'],
		searchUrl: 'https://www.addresses.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'PeopleConnect Holdings (H.I.G. Capital)',
		steps: [
			{ instruction: 'Go to the PeopleConnect suppression center.', url: 'https://suppression.peopleconnect.us/login' },
			{ instruction: 'Enter your email address and click Continue.' },
			{ instruction: 'Check your email and click the verification link.' },
			{ instruction: 'Enter your date of birth and agree to the terms.' },
			{ instruction: 'Enter your full name and select your record.' },
			{ instruction: 'Choose "Suppressed" in the Desired Behavior dropdown and click Save.' },
		],
		notes: 'Uses the same PeopleConnect suppression center as Intelius.',
	},

	// ─── LTVCO SUBSIDIARIES (share opt-out with BeenVerified) ────────

	{
		id: 'peoplelooker',
		name: 'PeopleLooker',
		url: 'https://www.peoplelooker.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://www.peoplelooker.com/f/optout/search',
		emailAddress: 'privacy@beenverified.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email'],
		searchUrl: 'https://www.peoplelooker.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'The Lifetime Value Company (LTVCO)',
		steps: [
			{ instruction: 'Go to the PeopleLooker opt-out page.', url: 'https://www.peoplelooker.com/f/optout/search' },
			{ instruction: 'Enter your name and search for your record.' },
			{ instruction: 'Find your record.' },
			{ instruction: 'Enter your email address and verify you are human.' },
			{ instruction: 'Click "Send Verification Email".' },
			{ instruction: 'Check your email and click the verification link.' },
		],
		notes: 'Same parent company as BeenVerified. Opting out of BeenVerified may also cover this site.',
	},
	{
		id: 'peoplesmart',
		name: 'PeopleSmart',
		url: 'https://www.peoplesmart.com',
		category: 'people-search',
		priority: 'high',
		difficulty: 'easy',
		optOutMethod: 'form',
		optOutUrl: 'https://www.beenverified.com/app/optout/search',
		emailAddress: 'privacy@beenverified.com',
		legalBasis: ['ccpa'],
		requiredInfo: ['name', 'email'],
		searchUrl: 'https://www.peoplesmart.com',
		verificationMethod: 'email',
		relistsAfterDays: 120,
		parentCompany: 'The Lifetime Value Company (LTVCO)',
		steps: [
			{ instruction: 'Go to the BeenVerified opt-out page (PeopleSmart redirects here).', url: 'https://www.beenverified.com/app/optout/search' },
			{ instruction: 'Enter your name and state, then search.' },
			{ instruction: 'Find your record.' },
			{ instruction: 'Enter your email and complete verification.' },
			{ instruction: 'Check your email and click the verification link.' },
		],
		notes: 'Same parent company as BeenVerified. Uses BeenVerified opt-out system.',
	},
];
