import type { ConversionPair } from './types';

export const allPairs: ConversionPair[] = [
	{
		slug: 'heic-to-jpg',
		sourceFormat: 'HEIC',
		targetFormat: 'JPG',
		sourceExtensions: '.heic,.heif',
		sourceMimeTypes: 'image/heic,image/heif',
		targetCodec: 'jpeg',
		defaultQuality: 85,
		supportsQuality: true,
		title: 'Convert HEIC to JPG',
		description: 'Convert HEIC photos from iPhone to universally compatible JPG',
		popular: true
	},
	{
		slug: 'heic-to-png',
		sourceFormat: 'HEIC',
		targetFormat: 'PNG',
		sourceExtensions: '.heic,.heif',
		sourceMimeTypes: 'image/heic,image/heif',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert HEIC to PNG',
		description: 'Convert HEIC photos to lossless PNG',
		popular: true
	},
	{
		slug: 'webp-to-png',
		sourceFormat: 'WebP',
		targetFormat: 'PNG',
		sourceExtensions: '.webp',
		sourceMimeTypes: 'image/webp',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert WebP to PNG',
		description: 'Convert WebP images to PNG for universal compatibility',
		popular: true
	},
	{
		slug: 'webp-to-jpg',
		sourceFormat: 'WebP',
		targetFormat: 'JPG',
		sourceExtensions: '.webp',
		sourceMimeTypes: 'image/webp',
		targetCodec: 'jpeg',
		defaultQuality: 85,
		supportsQuality: true,
		title: 'Convert WebP to JPG',
		description: 'Convert WebP to JPG for wider support',
		popular: false
	},
	{
		slug: 'png-to-webp',
		sourceFormat: 'PNG',
		targetFormat: 'WebP',
		sourceExtensions: '.png',
		sourceMimeTypes: 'image/png',
		targetCodec: 'webp',
		defaultQuality: 80,
		supportsQuality: true,
		title: 'Convert PNG to WebP',
		description: 'Convert PNG to WebP for smaller file sizes',
		popular: false
	},
	{
		slug: 'jpg-to-webp',
		sourceFormat: 'JPG',
		targetFormat: 'WebP',
		sourceExtensions: '.jpg,.jpeg',
		sourceMimeTypes: 'image/jpeg',
		targetCodec: 'webp',
		defaultQuality: 85,
		supportsQuality: true,
		title: 'Convert JPG to WebP',
		description: 'Convert JPG to WebP for web optimization',
		popular: false
	},
	{
		slug: 'png-to-jpg',
		sourceFormat: 'PNG',
		targetFormat: 'JPG',
		sourceExtensions: '.png',
		sourceMimeTypes: 'image/png',
		targetCodec: 'jpeg',
		defaultQuality: 85,
		supportsQuality: true,
		title: 'Convert PNG to JPG',
		description: 'Convert PNG to JPG, reducing file size',
		popular: false
	},
	{
		slug: 'jpg-to-png',
		sourceFormat: 'JPG',
		targetFormat: 'PNG',
		sourceExtensions: '.jpg,.jpeg',
		sourceMimeTypes: 'image/jpeg',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert JPG to PNG',
		description: 'Convert JPG to lossless PNG',
		popular: false
	},
	{
		slug: 'svg-to-png',
		sourceFormat: 'SVG',
		targetFormat: 'PNG',
		sourceExtensions: '.svg',
		sourceMimeTypes: 'image/svg+xml',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert SVG to PNG',
		description: 'Rasterize SVG to PNG at any resolution',
		popular: true
	},
	{
		slug: 'avif-to-png',
		sourceFormat: 'AVIF',
		targetFormat: 'PNG',
		sourceExtensions: '.avif',
		sourceMimeTypes: 'image/avif',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert AVIF to PNG',
		description: 'Convert AVIF to widely supported PNG',
		popular: false
	},
	{
		slug: 'avif-to-jpg',
		sourceFormat: 'AVIF',
		targetFormat: 'JPG',
		sourceExtensions: '.avif',
		sourceMimeTypes: 'image/avif',
		targetCodec: 'jpeg',
		defaultQuality: 85,
		supportsQuality: true,
		title: 'Convert AVIF to JPG',
		description: 'Convert AVIF to JPG',
		popular: false
	},
	{
		slug: 'png-to-avif',
		sourceFormat: 'PNG',
		targetFormat: 'AVIF',
		sourceExtensions: '.png',
		sourceMimeTypes: 'image/png',
		targetCodec: 'avif',
		defaultQuality: 65,
		supportsQuality: true,
		title: 'Convert PNG to AVIF',
		description: 'Convert PNG to AVIF for maximum compression',
		popular: false
	},
	{
		slug: 'jpg-to-avif',
		sourceFormat: 'JPG',
		targetFormat: 'AVIF',
		sourceExtensions: '.jpg,.jpeg',
		sourceMimeTypes: 'image/jpeg',
		targetCodec: 'avif',
		defaultQuality: 65,
		supportsQuality: true,
		title: 'Convert JPG to AVIF',
		description: 'Convert JPG to AVIF for smaller files',
		popular: false
	},
	{
		slug: 'jxl-to-png',
		sourceFormat: 'JPEG XL',
		targetFormat: 'PNG',
		sourceExtensions: '.jxl',
		sourceMimeTypes: 'image/jxl',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert JPEG XL to PNG',
		description: 'Convert JPEG XL to PNG',
		popular: false
	},
	{
		slug: 'bmp-to-png',
		sourceFormat: 'BMP',
		targetFormat: 'PNG',
		sourceExtensions: '.bmp',
		sourceMimeTypes: 'image/bmp',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert BMP to PNG',
		description: 'Convert BMP to compressed PNG',
		popular: false
	},
	{
		slug: 'gif-to-png',
		sourceFormat: 'GIF',
		targetFormat: 'PNG',
		sourceExtensions: '.gif',
		sourceMimeTypes: 'image/gif',
		targetCodec: 'png',
		defaultQuality: 95,
		supportsQuality: false,
		title: 'Convert GIF to PNG',
		description: 'Convert GIF to PNG',
		popular: false
	},
	{
		slug: 'tiff-to-jpg',
		sourceFormat: 'TIFF',
		targetFormat: 'JPG',
		sourceExtensions: '.tiff,.tif',
		sourceMimeTypes: 'image/tiff',
		targetCodec: 'jpeg',
		defaultQuality: 85,
		supportsQuality: true,
		title: 'Convert TIFF to JPG',
		description: 'Convert TIFF to compressed JPG',
		popular: false
	}
];

export function getPair(slug: string): ConversionPair | undefined {
	return allPairs.find((p) => p.slug === slug);
}
